### ISSUE TITLE
3 different NullReferenceException on extension loading

### ISSUE THREAD

**Issue by spider312** [scrubs767/GitStash#2] opened 2016-01-26 11:20 UTC
Hi

When i start Visual Studio Pro 2015 after installing this extension, i got an error message about an exception, and when i go to "Team explorer" > "Git stash" window i only got those errors (thus can't use this extension) : 

`System.NullReferenceException: Object reference not set to an instance of an object.
   at GitStash.ViewModels.PageViewModel..ctor(INavigateable page, IGitStashWrapper wrapper, Translator T)
   at GitStash.StashPage.Initialize(Object sender, PageInitializeEventArgs e) in C:\Users\scrub\Source\Repos\GitStash\GitStash\StashPage.cs:line 42
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerPageHost.Initialize(TeamExplorerPageContext context)`

`System.NullReferenceException: Object reference not set to an instance of an object.
   at GitStash.ViewModels.RecommendedActionsViewModel..ctor(IGitStashWrapper wrapper, ITeamExplorerBase page)
   at GitStash.Sections.RecommendedActionsSection.Initialize(Object sender, SectionInitializeEventArgs e) in C:\Users\scrub\Source\Repos\GitStash\GitStash\Sections\RecommendedActionsSection.cs:line 21
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerSectionHost.Initialize(Object context)`

`System.NullReferenceException: Object reference not set to an instance of an object.
   at GitStash.ViewModels.StashesViewModel..ctor(IGitStashWrapper git, ITeamExplorerBase page, Translator T)
   at GitStash.Sections.StashesSection.Initialize(Object sender, SectionInitializeEventArgs e) in C:\Users\scrub\Source\Repos\GitStash\GitStash\Sections\StashesSection.cs:line 34
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerSectionHost.Initialize(Object context)`

Visual studio version is 14.0.24720.00, GitStash version is 0.7

Let me know if i can provide more usefull information

Thanks in advance

**Comment by spider312** [comment] 2016-02-04 10:08
After updating to 0.8 i don't even have a "git stash" button in team explorer ...

**Comment by spider312** [comment] 2016-02-04 13:22
A new clue : i'm using professionnal version of Visual Studio, and a co-worker using community version don't have those bugs

**Comment by scrubs767** [comment] 2016-02-04 13:34
Open visual studio, do not open a project, click on the team explorer tab and click on the green plug next to the house icon at the top of the tab, take a screen shot and attach it to a message here please. Then click on the house icon at the top of the team explorer tab, take another screen shot and attach that also. If you can crop it to the size of the entire team explorer window, if not then resize the images.

**Comment by scrubs767** [comment] 2016-02-04 13:35
I run professional at work and community at home, both work.

**Comment by spider312** [comment] 2016-02-10 09:56
Asked screenshots : 

![vs_te_connect](https://cloud.githubusercontent.com/assets/2428133/12943979/e03b0a16-cfe4-11e5-9e29-305625b332a8.png)
![vs_te_home](https://cloud.githubusercontent.com/assets/2428133/12943980/e03d5410-cfe4-11e5-8bae-5ce34091d1f1.png)

**Comment by scrubs767** [comment] 2016-02-11 10:40
That looks good, Is there any text in the output window, make sure the drop down that says "show output from" has Git Stash selected.

**Comment by scrubs767** [comment] 2016-02-11 10:43
Also, try opening a solution that has a git repository, the button will not show unless there is a git repository open in team explorer. Team explorer is a little weird in this respect, even though a solution is not open TE will have an open git connection.

**Comment by spider312** [comment] 2016-02-17 10:38
There is absolutely no messages in the "show output" window from git stash, and when my Team Explorer is connected to a git repository, the button isn't appearing in the "Team Explorer" tab

**Comment by scrubs767** [comment] 2016-02-17 10:56
Sounds like its not installed

**Comment by spider312** [comment] 2016-02-17 14:15
Well, i have "Git Stash" in list on top of the "output" window, and extension manager tells me it's installed ... So for me it souds like it's installed

**Comment by scrubs767** [comment] 2016-02-17 14:17
Well, I'm sorry without more information, I can not help, you could
download the source, build it and debug it, if you find a bug I'll be happy
to fix it. For now I'm closing as unable to reproduce

**Closed** 2016-02-17 14:18 UTC
Labels: invalid
